version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'Powerplex'
    commit-message:
      prefix: 'build(npm)'
    groups:
      zag-js:
        patterns:
          - '@zag-js/*'
      testing:
        patterns:
          - '@testing-library/*'
          - '@testing-library'
          - 'vitest'
          - '@vitest/*'
          - '@vitest'
          - '@playwright/*'
          - '@playwright'
      storybook:
        patterns:
          - '@storybook/*'
          - '*storybook*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - '*vite*'
      dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@zag-js/*'
          - '@testing-library/*'
          - '@testing-library'
          - 'vitest'
          - '@vitest/*'
          - '@vitest'
          - '@playwright/*'
          - '@playwright'
          - '@storybook/*'
          - '*storybook*'
          - 'vite'
          - '@vitejs/*'
          - '*vite*'
        update-types: ['minor', 'patch']
      major:
        patterns:
          - '*'
        update-types: ['major']
